# Generated by Django 3.1.3 on 2021-10-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_been_employed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
