# Generated by Django 3.1.3 on 2021-10-13 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_accept_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='has_been_employed',
            field=models.BooleanField(default=False),
        ),
    ]
