# Generated by Django 3.1.3 on 2021-10-14 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20211013_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legal_conditions',
        ),
    ]
