# Generated by Django 3.1.7 on 2021-10-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_opinion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
