# Generated by Django 3.1.7 on 2021-10-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='teleworking',
            field=models.BooleanField(default=False),
        ),
    ]
