# Generated by Django 3.1.7 on 2021-10-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joboffer', '0002_joboffer_teleworking'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='lower_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='upper_salary',
            field=models.IntegerField(default=20),
        ),
    ]
