# Generated by Django 3.1.7 on 2021-10-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('journey', models.CharField(choices=[('jornada completa', 'Complete'), ('media jornada', 'Hald')], default='jornada completa', max_length=50)),
            ],
        ),
    ]
