# Generated by Django 3.1.7 on 2021-10-09 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='journey',
            field=models.CharField(choices=[('jornada completa', 'Complete'), ('media jornada', 'Half')], default='jornada completa', max_length=50),
        ),
    ]
