# Generated by Django 3.1.7 on 2021-10-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20211009_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='company',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='web_url',
            field=models.CharField(default='http://google.es', max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='workers',
            field=models.IntegerField(default=0),
        ),
    ]
